version: "3.9"

services:
  ftword:
    build:
      context: ./wordpress
    container_name: ftword
    environment:
      - WORDPRESS_DB_HOST=localhost
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=rootpass
      - WORDPRESS_DB_NAME=test
    volumes:
      - wp_data:/var/www/html
    networks:
      - wpnet

  ftnginx:
    build:
      context: ./nginx
    container_name: ftnginx
    depends_on:
      - ftword
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - wp_data:/var/www/html:ro
    networks:
      - wpnet

networks:
  wpnet:

volumes:
  wp_data:
